added cards to print
PerfectPark1/PerfectPark pull request #67
Opened 2020-06-03 18:59 UTC by CGMcBride

I updated the cards on the page to print, I ended up having to change the design slightly just so it will work. Also added in rows and cols so that the park info wont overlap on the picture. I resized the image so that it will not take as long to load on the screen. The navigation bar has been updated with our logo and I updated the css so that all the words have on the screen will look more centered between the user state selection and search button.

2020-06-03 22:47 UTC, kholder777 requested changes
Resolved disputes between branch and master.
Please confirm corrections are indeed correct.

2020-06-03 23:17 UTC, steppinonland requested changes
i looked through it and noticed a few bugs that need to get fixed:
there are no cards displaying. I tried multiple states. no parks are displaying.
i specifically took out the ‘weather information’ tab on the nav bar. i did that last night when designing the info page. the reason why i did that is because the user must select a state first so that there’s weather data to display at all. the weather information section of the nav bar really doesn’t have a purpose, since the only way to navigate to weather is to go through the following steps:
select state
click on a park
button will take user to info page to view the weather for that park.
i hope that makes sense! it’s important that we’re all understanding the flow correctly, because we will be graded on that.

2020-06-04 00:42 UTC, steppinonland approved these changes

2020-06-04 05:25 UTC, kholder777 approved these changes

2020-06-04 07:12 UTC, jordanalexis6 approved these changes
Niceeee

2020-06-04 07:13 UTC, merged